# Generated by Django 5.0.6 on 2024-05-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
    ]
